if (DEFINED ENV{BOARD_CONFIG})
    set(BOARD_CONFIG $ENV{BOARD_CONFIG})
    message("Using BOARD_CONFIG from environment ('${BOARD_CONFIG}')")
else()
    if (NOT BOARD_CONFIG)
        set(BOARD_CONFIG "default")
        message("BOARD_CONFIG not specified. Default to \"default\"")
    else()
        message("BOARD_CONFIG is ${BOARD_CONFIG}.")
    endif()
endif()
