#ifndef CONFIG_H_
#define CONFIG_H_

#include "FreeRTOSConfig.h"

#define CONFIG_KEYBOARD_NAME "Pico Keyboard"

#define CONFIG_ENABLE_ROTARYENCODER 1
#define CONFIG_ENABLE_DISPLAY 1

#define CONFIG_ENABLE_JOYSTICK 1

#if CONFIG_ENABLE_JOYSTICK

#define CONFIG_JOYSTICK_GPIO_X 28
#define CONFIG_JOYSTICK_GPIO_Y 27
#define CONFIG_JOYSTICK_FLIP_X_DIR 0
#define CONFIG_JOYSTICK_FLIP_Y_DIR 0
#define CONFIG_JOYSTICK_SMOOTH_BUFFER_LEN 3

#endif /* CONFIG_ENABLE_JOYSTICK */

#define CONFIG_SCAN_TICKS 5
#define CONFIG_SLOW_TICKS 50
#define CONFIG_DEBOUNCE_TICKS 15

#define CONFIG_GPIO_SINK_DELAY_US 1

#define CONFIG_TASK_STACK_SIZE 5120
#define CONFIG_TASK_PRIORITY (configMAX_PRIORITIES - 2)

#define CONFIG_USB_VID 0xeceb
#define CONFIG_USB_PID 0x3026
#define CONFIG_USB_POLL_MS 1
#define CONFIG_USB_VENDER_NAME "PicoMK"
#define CONFIG_USB_PRODUCT_NAME CONFIG_KEYBOARD_NAME
#define CONFIG_USB_SERIAL "1234"

// Enable or disable USB serial debug

#define CONFIG_DEBUG_ENABLE_USB_SERIAL 1

#if CONFIG_DEBUG_ENABLE_USB_SERIAL

#define CONFIG_DEBUG_USB_SERIAL_CDC_CMD_MAX_SIZE 8
#define CONFIG_DEBUG_USB_BUFFER_SIZE 64
#define CONFIG_DEBUG_USB_TIMEOUT_US 500000

#define CONFIG_DEBUG_LOG_LEVEL 3

#else

#define CONFIG_DEBUG_LOG_LEVEL 0  // Disable all logs

#endif /* CONFIG_DEBUG_ENABLE_USB_SERIAL */

#endif /* CONFIG_H_ */
