#ifndef CONFIG_H_
#define CONFIG_H_

#include "FreeRTOSConfig.h"

#define CONFIG_ENABLE_ROTARYENCODER 1
#define CONFIG_ENABLE_JOYSTICK 1
#define CONFIG_ENABLE_DISPLAY 1

#define CONFIG_SCAN_TICKS 5
#define CONFIG_DEBOUNCE_TICKS 15

#define CONFIG_GPIO_SINK_DELAY_US 1

#define CONFIG_TASK_STACK_SIZE 5120
#define CONFIG_TASK_PRIORITY (configMAX_PRIORITIES - 2)

#endif /* CONFIG_H_ */