#ifndef CONFIG_H_
#define CONFIG_H_

#include "FreeRTOSConfig.h"

#define CONFIG_KEYBOARD_NAME "Pico Keyboard V0.4"

#define CONFIG_SCAN_TICKS 5
#define CONFIG_SLOW_TICKS 50
#define CONFIG_DEBOUNCE_TICKS 15

#define CONFIG_GPIO_SINK_DELAY_US 1

#define CONFIG_TASK_STACK_SIZE (configMINIMAL_STACK_SIZE * 4)
#define CONFIG_TASK_PRIORITY (configMAX_PRIORITIES - 2)

#define CONFIG_USB_VID 0xeceb
#define CONFIG_USB_PID 0x3026
#define CONFIG_USB_POLL_MS 1
#define CONFIG_USB_VENDER_NAME "PicoMK"
#define CONFIG_USB_PRODUCT_NAME CONFIG_KEYBOARD_NAME
#define CONFIG_USB_SERIAL_NUM "1234"

#define CONFIG_FLASH_FILESYSTEM_SIZE (32 * 4096)
#define CONFIG_FLASH_JSON_FILE_NAME "config.json"

// Enable or disable USB serial debug

#define CONFIG_DEBUG_ENABLE_USB_SERIAL 0

#if CONFIG_DEBUG_ENABLE_USB_SERIAL

#define CONFIG_DEBUG_USB_SERIAL_CDC_CMD_MAX_SIZE 8
#define CONFIG_DEBUG_USB_BUFFER_SIZE 64
#define CONFIG_DEBUG_USB_TIMEOUT_US 500000

#define CONFIG_DEBUG_LOG_LEVEL 0

#else

#define CONFIG_DEBUG_LOG_LEVEL 0  // Disable all logs

#endif /* CONFIG_DEBUG_ENABLE_USB_SERIAL */

#endif /* CONFIG_H_ */
